### ISSUE TITLE
Create and update kafka connect in standalone mode over REST API

### ISSUE THREAD

**Issue by alextsm** [confluentinc/rest-utils#35]
Hi, 
I’m trying to create and update kafka connect in standalone mode over REST API.
For create new connector, I use the request:
curl -X POST -H "Content-Type: application/json" --data '{"name2": "local-console-source4", "config": {"connector.class":"org.apache.kafka.connect.file.FileStreamSourceConnector", "tasks.max":"1", "topic":"connect-test123456789", "file":"/etc/kafka/test8.txt"}}' http://localhost:8083/connectors

The new connector created without any problems.

But, what I should change in the request if I need to update only a file config parameter without recreated the connector?

I’m trying to update with the request:
curl -X POST -H "Content-Type: application/json" --data '{"config": {"file":"/etc/kafka/test8.txt"}}' http://localhost:8083/connectors/local-file-source/config
but:
 
[root@pnode1 ~]# curl -X POST -H "Content-Type: application/json" --data '{"config": {"file":"/etc/kafka/test8.txt"}}' http://localhost:8083/connectors/local-file-source/config

Error 405 
HTTP ERROR: 405
Problem accessing /connectors/local-file-source/config. Reason:
Method Not Allowed
Powered by Jetty://

**Comment by ewencp** [comment]
@alextsm Since you're sending a complete new config, the HTTP verb we use is `PUT`. See http://docs.confluent.io/2.0.1/connect/userguide.html#put--connectors-%28string-name%29-config for details. The reason this differs from the initial request is that the `POST` is to the collection resource (`/connectors`) which is not a full update of that resource, instead it creates a new sub-resources (`/connectors/local-filesource`).

**Comment by alextsm** [comment]
Thanks

**Comment by manojkumarsadhu** [comment]
did you solve the problem. how can you update that config file?
