### ISSUE TITLE
Check if a file transfer has been completed to kafka

### ISSUE THREAD

**Issue by alextsm** [confluentinc/rest-utils#36]
Hi, 
I need to understand when a file transfer has been completed to kafka with kafka-connect.
It seems the only way to do it is (without check some data in a topic) check an offset-file. 
When a file transfer has been completed a new string added to an offset-file. 
But an offset-file has binary file format. How can I read some data from an offset-file? 
Perhaps, can I use a REST interface? 
Are there some other way to check if a file transfer has been completed to kafka?

**Comment by ewencp** [comment]
@alextsm The file connector in Kafka Connect streams data continuously as data is appended to a file, so it never actually considers the transfer to be "complete". There's not currently a way to tell if you've reached the current end of the file.

This is quite similar to Kafka itself. Even if you did look up the current last offset, that doesn't give you a way to be *sure* you've read to the end since producers could always be adding more messages.

There might be use cases where you know no more data will be written, e.g. after a log file has been rolled and you can guarantee it won't be written to anymore, but currently the simple implementation of the file source doesn't support exposing that.

By the way, GitHub issues aren't great for questions like this, and this repository also isn't relevant to your question (I caught it because I happen to watch both repositories, but your question easily could have been lost). You might also be interested in our [mailing list](https://groups.google.com/forum/#!forum/confluent-platform), which might be a better forum for questions like this.
